apiVersion: apps/v1
kind: Deployment

metadata:
  name: grafana

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: grafana

  template:
    metadata:
      labels:
        app: grafana

    spec:
      containers:
      - name: grafana

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        ports:
        - containerPort: 3000

        volumeMounts:
        - name: datasource-config
          mountPath: /etc/grafana/provisioning/datasources

      volumes:
      - name: datasource-config

        configMap:
          name: grafana-datasources