namespace: dev

frontend:
  replicaCount: 1

  image:
    repository: rishikkk/frontend
    tag: v1

  service:
    port: 80
    targetPort: 8080

backend:
  replicaCount: 1

  image:
    repository: rishikkk/backend
    tag: v1

  service:
    port: 3000
    targetPort: 3000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"

  limits:
    cpu: "500m"
    memory: "512Mi"

hpa:
  minReplicas: 1
  maxReplicas: 3
  cpuUtilization: 70

cronjob:
  schedule: "*/5 * * * *"

