apiVersion: v1
kind: ConfigMap

metadata:
  name: prometheus-config

data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:

      - job_name: "backend"

        metrics_path: "{{ .Values.scrape.metricsPath }}"

        static_configs:
          - targets:
              - "{{ .Values.scrape.target }}"