apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.frontend.replicaCount }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0        # ✅ don't create extra pod during update
      maxUnavailable: 1  # ✅ kill old pod first on resource-constrained nodes

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: frontend

        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"

        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}

          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}

        env:
          - name: BACKEND_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: BACKEND_URL